### PR TITLE
Image decoding

### LINKED ISSUE #215: Image not always rendered
### Description
Often some parts of the scene are not rendered on Android. Debug & Release
Tested in web with no issues.

### Steps To Reproduce
1. create project from example
2. add car.rive to assets
3. add assets/car.riv to pubspec
4. run example

<details>
 <summary>Example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:rive/rive.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final RiveAnimationController _controller;
  bool _isPlaying = false;

  @override
  void initState() {
    super.initState();
    _controller = OneShotAnimation(
      'drive',
      autoplay: false,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            SizedBox(
              height: 200,
              child: RiveAnimation.asset(
                'assets/car.riv',
                controllers: [_controller],
              ),
            ),
            ElevatedButton(
              onPressed: _isPlaying
                  ? null
                  : () {
                      _controller.isActive = true;
                      setState(() {
                        _isPlaying = true;
                      });
                    },
              child: const Text('Start'),
            ),
            ElevatedButton(
              onPressed: _isPlaying
                  ? () {
                      Navigator.of(context).pushReplacement(
                        MaterialPageRoute(
                          builder: (context) => const SecondPage(),
                        ),
                      );
                    }
                  : null,
              child: const Text('Next page'),
            ),
          ],
        ),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).pushReplacement(
              MaterialPageRoute(builder: (context) => const MyHomePage()),
            );
          },
          child: const Text('Home'),
        ),
      ),
    );
  }
}

``` 

</details>

#### Source `.riv`/`.rev` file
[car.zip](https://github.com/rive-app/rive-flutter/files/8525488/car.zip)

### Expected behavior
The image is rendered the same as on rive.app, every time.

#### Screenshots
<details>

<-- If applicable, add screenshots to help explain your problem. -->
Screenshot_2022-04-20-22-06-26-32_307f4184460b001ebff3ecdd8a4bcf05
Screenshot_2022-04-20-22-07-19-24_307f4184460b001ebff3ecdd8a4bcf05
Screenshot_2022-04-20-22-07-24-20_307f4184460b001ebff3ecdd8a4bcf05
Screenshot_2022-04-20-22-07-32-23_307f4184460b001ebff3ecdd8a4bcf05

</details>

### Device & Versions (please complete the following information)
- Device: [Android Emulator, OnePlus 8T] 
- OS: [e.g. Android SDK API Level 30, Android 12]
- Flutter Version: 
```
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (2 days ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

### PR DESCRIPTION
**Pull request by umberto-sonnino**
- Fixes the Android build updating to various new versions
- Adds listeners so that when an image completes decoding it can mark drawable as dirty on completion

Fixes #215

### CODE REVIEW

File: lib/src/rive_core/shapes/image.dart [hunk 1]
```diff
@@ -38,8 +38,9 @@ class Image extends ImageBase
 
   @override
   void draw(ui.Canvas canvas) {
-    var uiImage = asset?.image;
+    final uiImage = asset?.image;
     if (uiImage == null) {
+      print('No image yet?! ${asset?.name} $uiImage');
```
Comment (mjtalbot) [inline lib/src/rive_core/shapes/image.dart:43]: we keeping this?

File: lib/src/rive_core/assets/image_asset.dart [hunk 2]
```diff
@@ -12,17 +12,31 @@ class ImageAsset extends ImageAssetBase {
...
   Future<void> decode(Uint8List bytes) {
-    var completer = Completer<void>();
+    final completer = Completer<void>();
     ui.decodeImageFromList(bytes, (value) {
       _image = value;
       completer.complete();
+
+      // Tell listeners that the image is ready to be drawn: mark them dirty.
+      _decodeListeners
+        ?..forEach((e) => e.context.markNeedsAdvance())
```
Comment (mjtalbot) [inline lib/src/rive_core/assets/image_asset.dart:38]: we mark the whole file as dirty, probably enough

File: lib/src/rive_core/shapes/image.dart (hunk 1 above)
Comment (umberto-sonnino) [reply lib/src/rive_core/shapes/image.dart]: Aaaaand it's gone 😄

File: lib/src/rive_core/shapes/image.dart [hunk 3]
```diff
@@ -101,6 +101,9 @@ class Image extends ImageBase
   void copy(covariant Image source) {
```
Comment (mjtalbot) [inline lib/src/rive_core/shapes/image.dart:100]: in what context does copy get called?. I'm not 100% on how ties ties back to the image being decoded. 

but i'm guessing we create Image components, and when we draw them their asset's not got the .image yet. so we need to make sure we get dirty when the image is actually loaded..

**Review by mjtalbot — APPROVED** [review]
lgtm. bit of a rubber stamp, but this seems quite sensible if i understand it right. 

would *love* a test. too complex to get something in?

File: lib/src/rive_core/shapes/image.dart (hunk 3 above)
Comment (umberto-sonnino) [reply lib/src/rive_core/shapes/image.dart:100]: iirc, this is called when making an artboard instance: every object is cloned and the data is copied over.
Image reading/decoding can take some time, though, and some images get copied without the bytes being present, that's why they don't get drawn.
